### ISSUE TITLE
Soundcloud Support

### ISSUE THREAD

**Issue by zvy5** [orsou/discord-music-bot#1]
It would be quite nice to be able to play music through links from soundcloud or other music streaming platforms.

**Comment by orsou** [comment]
I'm sorry to tell you this but I don't work on this project anymore. It has never really been used that much by anyone, not even myself and it's not compatable with the new Discord API. I'm saving others and myself a lot of time by discontinuing this project. There are far better alternatives out there that have already implementet the new Discord API, other music streaming services and are overall just way simpler and better to use. This project is a mess considering it's usability and user experience.

**Comment by orsou** [comment]
Try [SudhanPlayz's Bot](https://github.com/SudhanPlayz/Discord-MusicBot) as an alternative or some of the others you find online.
